### PR TITLE
Update site to use new Code of Conduct

### PR DESCRIPTION
**Pull request by valencik**
Following the [approval of the new Typelevel Code of Conduct](https://github.com/typelevel/governance/pull/129), this PR updates the site to use that new Code of Conduct and link to the Enforcement Procedures in the governance repo.
Also we remove older Code of Conduct material to avoid confusion.

### CODE REVIEW

**Comment by valencik** [comment]
Perhaps of note, this will break the https://typelevel.org/conduct/ link, but I am not sure how important that is.
That page currently does not render well, and it displays a deprecated CoC.
Redirects in jekyll land do not seem straightforward without plugins, so I don't really want to go down that route personally.

**Review by samspills — APPROVED** [review]

**Comment by SethTisue** [comment]
Will there be a blog post too?

**Comment by valencik** [comment]
> Will there be a blog post too?

Yes.

**Review by jducoeur — APPROVED** [review]

**Comment by valencik** [comment]
Blog post added. It's mostly the description for the original PR which already had lots of good detail.

**Review by samspills — APPROVED** [review]

**Review by mpilquist — APPROVED** [review]

**Pull request merged**
