### PR TITLE
Remove WartRemover

### PR DESCRIPTION
**Pull request by puffnfresh**

### CODE REVIEW

**Comment by dwijnand** [comment]
How come @puffnfresh?

**Comment by folone** [comment]
Yeah, what is going on? Also in https://github.com/typelevel/typelevel.github.com/pull/35. Is there a discussion somewhere? /cc @milessabin @propensive @larsrh

**Comment by non** [comment]
I just saw Brian's PR and figured that if he wanted WartRemover gone, I should remove it.

I assume this is fallout from the Scalaz/CoC situation, although I haven't spoken to Brian about it. I apologize if I'm assuming wrong.

**Comment by non** [comment]
I will let @milessabin speak about #35, although I know that Paul Chiusano specifically requested that scalaz-stream be removed.

**Comment by puffnfresh** [comment]
Just don't want to be associated with any of this.

**Comment by puffnfresh** [comment]
But would still like to work on WartRemover, if I want to.

**Comment by milessabin** [comment]
I won't say much here ... I don't want to preempt the announcement which will be coming shortly.

**Pull request merged**
