### PR TITLE
NYC: accepted talks

### PR DESCRIPTION
**Pull request by larsrh**
~~Do not merge yet. 3 speakers pending confirmation.~~

### CODE REVIEW

**Comment by longcao** [comment]
HI @larsrh, thanks for setting this up! I'd like to amend my description to be a little less stiff and square (I wrote it quickly and didn't know it would be public 😁)

> Long Cao is a software engineer focusing on Scala, Spark, and data engineering and has been in New York for the last 5 years. He cares deeply about showing newcomers the benefits of Scala and functional programming. On his off time likes to enjoy climbing, Rocket League, music, sports, and coffee.

**Comment by larsrh** [comment]
Currently away from keyboard, will fix later today.

**Comment by adelbertc** [comment]
Please update my bio :D 

> Adelbert is an engineer at Box where he attempts to reliably copy bytes from one machine to another. He enjoys writing pure functional programs, teaching functional programming, and learning more about computing.

**Comment by larsrh** [comment]
@adelbertc @longcao Fixed now.

**Comment by longcao** [comment]
@larsrh Thank you! 👍

**Comment by adelbertc** [comment]
👍  Thanks Lars!

**Pull request merged**
