### PR TITLE
tut improvements

### PR DESCRIPTION
**Pull request by larsrh**
~I'm also trying to get compiler plugins to work.~

### CODE REVIEW

**Comment by larsrh** [comment]
@LukaJCB @gvolpe If you're so inclined, it'd be great if you could test this out on one of your blog posts.

Here's an example diff to enable `kind-projector`:

```diff
--- a/posts/2018-04-13-rethinking-monaderror.md
+++ b/posts/2018-04-13-rethinking-monaderror.md
@@ -12,6 +12,8 @@ tut:
   binaryScala: "2.12"
   dependencies:
     - org.typelevel::cats-core:1.1.0
+  plugins:
+    - org.spire-math::kind-projector:0.9.8
 ---
```

**Comment by larsrh** [comment]
@LukaJCB I didn't try it yet though :grin:

**Comment by ceedubs** [comment]
@larsrh this is really cool! I gave it a spin with a post that uses kind-projector and it worked great.

**Comment by gvolpe** [comment]
Will give it a try soon, thanks @larsrh !

**Comment by larsrh** [comment]
Excellent! Awaiting your follow-up PRs :smile:

**Pull request merged**
