### PR TITLE
remove Typelevel Scala from projects list

### PR DESCRIPTION
**Pull request by SethTisue**
it's dead/archived

### CODE REVIEW

**Review by jducoeur — APPROVED** [review]

**Review by johnynek — APPROVED** [review]

**Comment by rossabaker** [comment]
There are actually a lot of archived projects.  I marked them all in the front matter with `archive`, but we're not doing anything special to render them.  I wasn't sure if we wanted to keep them for historical interest or just banish them.

**Comment by SethTisue** [comment]
> I wasn't sure if we wanted to keep them for historical interest

it's not worth making life more difficult for newcomers and casual users, IMO

**Comment by rossabaker** [comment]
In that case, there are [several more](https://github.com/typelevel/typelevel.github.com/search?q=archived).

**Comment by SethTisue** [comment]
> In that case, there are several more

#390

**Pull request merged**
