### PR TITLE
New post: "Nested existentials"

### PR DESCRIPTION
**Pull request by S11001001**
Fifth in a series on type parameters and members, for posting on July 27. Preceded by #46.

NB: Links to the previous post will not work on GH, because they use `post_url`, which only works on the site.

### CODE REVIEW

**Comment by puffnfresh** [comment]
The backticks in paragraph "The reason you can’t invoke..." aren't rendering on GitHub - might have a Markdown problem there.

**Comment by S11001001** [comment]
@puffnfresh Yeah, that happens in `div side-note` as corrected in 3c94791. A non-hack solution would be nice, though.

**Comment by S11001001** [comment]
Here are the "full relationships", rendered with Mathjax:

tptm 5 derivations

Does this mishmash of `code` and $$ look good here?

**Comment by S11001001** [comment]
Well, I did the hacky version in 3d18e85, @puffnfresh.

**Pull request merged**
