### PR TITLE
Fix bugs in Libra post

### PR DESCRIPTION
**Pull request by ashawley**
I tried to follow the code examples, and got tripped up on some things.

Hopefully, the following changes are useful to others, as well.

This is a really great article.  Thank you!  I'm looking forward to learning more about Libra.

### CODE REVIEW

**Comment by larsrh** [comment]
Review by @zainab-ali

**Comment by zainab-ali** [comment]
My mistake!  I really should have compiled this with tut beforehand.
I'm going to recompile with tut later to make sure that there are no more errors.

Thanks for fixing these!

**Comment by larsrh** [comment]
Thanks, @ashawley!

@zainab-ali Would you mind submitting an update to this repo to tut-ify the post?

**Comment by zainab-ali** [comment]
I've now submitted an update #181

**Comment by ashawley** [comment]
Wow, converting the examples to tut they are sure to compile.  To be honest, I didn't mind that a certain amount of the code and the errors weren't entirely accurate.  The early examples are missing infix notation, now.  And the type errors are less succinct.  Very cool, though. Thanks for making the code compile.

**Pull request merged**
