### PR TITLE
remove ensime from the project list.

### PR DESCRIPTION
**Pull request by fommil**
These past few days I've been thinking a lot about why ENSIME is a member of Typelevel. My soul searching has led me to conclude that I don't feel that ENSIME is a good fit for a formal relationship with Typelevel and I've been sitting on this post over the weekend.

I'd like to say that this has been a very difficult decision to reach and I fear for any fallout. Therefore I request that this is not publicised (at least not loudly).

I have discussed this with other long term contributors and we feel that we have always been the "oddball project" who are out of place in the Typelevel line-up, so it is perhaps for the best. We're all still committed to fostering an inclusive environment.

I truly hope that this does not affect my personal friendship with anybody in Typelevel - especially those I know in real life and continue to socialise with at conferences. I feel I owe you an explanation, and I am happy to provide the following.

## Functional Programming

There is no kidding ourselves that ENSIME could ever be an example of functional programming. Grep counts 155 references to `Actor` and 293 to `var`. Rewriting to use cats / freestyle and fs2 (which I would *love* to do) is a major undertaking that is frankly a pipe dream.

The client code is mostly in languages that don't even have types or compilers.

ENSIME has no plans to be prescriptive about functional programming style for users. The majority of ensime users and contributors are more familiar with the mainstream Lightbend stack.

In this regard, I do not believe ENSIME qualifies for [Typelevel Mission Statement](https://github.com/typelevel/general/issues/36) points: "Pure, typeful, functional programming in Scala" or "Accessible and idiomatic learning resources".

We could argue that ENSIME is somehow special and is trying to improve the tooling for functional programmers, but despite our efforts to drum up support for contributions to the presentation compiler (see [ensime's presentation compiler testing library](https://github.com/ensime/pcplod), [implicit derivation hack](https://github.com/ensime/ensime-plugin-implicits) and discussing plans at conferences to create a `pccompile` sbt task) it has gained no interest or traction. That is a clear indicator to me that there just aren't enough Typelevel members who are interested in contributing to ENSIME.

This is not to say that ENSIME is changing any plans to support functional programming... I'd personally like to see improvements in this area, especially now that I'm learning functional programming properly. Ironically, it'll probably get a lot better over the coming year.

## Libre Software

I can agree with "Independent, free/libre and open source software". I am proudly a Libre Software supporter when donating my time. When I'm at work, I'm pretty much a gun slinging IPR mercenary, I am able to reconcile these two extremes.

I don't speak for everybody in ENSIME, but I can say that it is a compromise for me to be part of an organisation that **encourages** permissive licenses such as MIT, BSD or Apache 2.0 over copyleft licenses such as MPL and GPL. Richard Stallman asked me if I would like to hand over ownership of ensime to GNU and - on a purely political level - it appeals to me much more than any other movement. I don't think he quite understood what a type was, though... he did ask if scala "was another kind of lisp".

## Political Agenda

The thread on FCoP has been a revelation to me, regardless of the outcome. I probably won't use the FCoP going forwards simply because I fear it will look like I am picking sides, I am not.

ENSIME will be reverting to the minimal Emacs Conduct rules, which effectively changes nothing because it's still ultimately up to muggins to enforce. If anything gets too complicated, I'll just pull the plug on the whole thing, my time with my family is more precious to me than any online community and I will not promise anything more than this.

There appears to be a wide range of interpretations of the Typelevel Code of Conduct and Typelevel's political goals. [Travis' comment](https://github.com/typelevel/general/issues/74#issuecomment-302950747) is spot on. The politics of Typelevel are not well-defined enough for anybody outside of the [core group](https://github.com/typelevel/general/issues/16) to know what Typelevel stands for. I do not feel that I can support a political agenda that I don't understand. Maybe I would if I understood what it was, but I just honestly don't know what it is.

We have **never** had a discrimination problem in the ensime gitter channels or github tickets. Making this the focus of the FCoP debate is ridiculous to me. The only problem we have is with insulting and rude users who treat me and other contributors as if they are paying customers. This has improved dramatically since I wrote about the [Open Source Entitlement Complex](https://medium.com/@fommil/the-open-source-entitlement-complex-bcb718e2326d) and refer to it throughout the documentation, which I also rewrote (instead of spending time with my family, I like to keep pointing that out because the sacrifice is lost on those who continue to shame me as a "user blamer"). The entire concept of Nazis showing up and taking over the ensime channel is utterly and ludicrously laughable, I don't understand the obsession.

I grew up in Northern Ireland, a country divided by a small group of religious fanatics on both sides who do not listen to each other, but ultimately wanted the same thing: access to a good quality of life for themselves and their children. They shouted at each other and blew each other up for several decades. The split in the Scala functional programming community (roughly: no-platform vs freedom of speech) is a very mild caricature of this, but the exact same mindsets are there. I am not picking any side, I am doing the equivalent of leaving for my own island where I sing the Free Software Song all day long. That's exactly how I solved the Northern Ireland problem: I just left the country.

## Overreach

I am **extremely** concerned about statements like "nor would I be allowed to send an email to the employer".

I absolutely cannot agree to be part of an organisation that uses this level of escalation. I've seen this happen, I've seen it ruin careers, you have no idea how the employer will respond and there is no right to a fair trial. It's an absolute abuse of power and social standing, I want no part of it. Combined with the lack of clarification around what is considered to be a violation of the Code of Conduct, this is a ticking time bomb.

It is conceivable that I have a bad day, say something rude on a gitter channel (probably along the lines of RTFM), find out that somebody emails my customer to complain and this tumbles into financial loss impacting my mortgage. By having agreed to the Typelevel Code of Conduct, a court may rule that I was aware of the risks and therefore I accepted the liability of financial loss. To be clear, I do not accept this level of liability, nor should anybody else, and I will take legal action against anybody who does anything remotely like this. I have my wife's full support (she's a lawyer) on this matter and it is her recommendation that I distance myself from any organisation (including Typelevel) who wish to hold this level of power.

If Typelevel were to clarify their position on all the above, as well as clarify how decision making happens, then we can consider ENSIME for re-admission on technical merit.

## Practicalities

There are several practical matters to attend to.

This PR addresses the link from Typelevel to the ENSIME projects.

~~I will address the link from the ENSIME project to Typelevel in my own time over the coming weeks (I have very poor internet connection at the moment, extremely limited time, and a lot of travel).~~ done

`ensime.typelevel.org` hosts the assembly jars. I request that we leave this in place until I complete https://github.com/ensime/ensime-server/issues/1779

Lars has kindly offered to propose [Debugging Position Information](https://github.com/scalacenter/advisoryboard/blob/master/proposals/011-debugging-symbols.md) to the Scala Center Advisory Board. I would hope that this will still be possible. We can arrange for Bill to propose it instead if Lars is no longer willing to make this proposal, which I feel would be of benefit to the entire community (and particularly helpful for scalac developers).

### CODE REVIEW

**Comment by kailuowang** [comment]
> I am extremely concerned about statements like "nor would I be allowed to send an email to the employer".
 I don't think TLCoC ever state such thing. The escalation it mentions is local law enforcement. The context of your quote is not included here, but I believe it's about whether a harassment victim is allowed to
 make such action. TLCoC does not punish a member who took that action(unless it can be treated as unbased and thus a harassment itself). Why should it? A helpless harassment victim doesn't have many ways to protect themselves.

**Comment by milessabin** [comment]
@kailuowang agreed. However this ticket isn't the right place for such a discussion.

**Comment by fommil** [comment]
The quote is from Lars on the FCoP ticket in the context of being a Typelevel community member. Since he is a community moderator, I expect that his interpretation of the TL-CoC is somewhat different to yours. Most codes of conduct explicitly state something along the lines of "the maximum penalty is a temporary or permanent ban", but the TL-CoC does not. This never covers illegal activity, which we are duty bound to report to the authorities.

Miles is correct, this is not the place to discuss this. Clarification would be appreciated and perhaps you could open a ticket on `typelevel/general` to discuss what the limits are and ensure that all community leaders are aware of the agreed limits, whatever they may be.

Regardless, I would hate for anybody to read this deeply personal message that I have written and believe that I am storming out over this one point, when I am not. Had I expected any response at all I could have hoped for a "sorry to see you go", I'm not here for an argument. :man_shrugging:

**Comment by ceedubs** [comment]
Associating a project with Typelevel is completely voluntary. I don't have merge rights to this repo myself, but 👍 to merging this promptly. @fommil it's clear that you've arrived at your decision after putting a lot of thought into this. I hope to still see your name around from time to time.

**Comment by BennyHill** [comment]
Rather than say "goodbye", I'd rather say "au revoir" :heart:

**Comment by milessabin** [comment]
Just to echo the sentiments above, we're all sorry to see you go, and would like to assure you that the door is open for you to return in future should you choose to.

**Pull request merged**
