### PR TITLE
Apply new layout from 47D

### PR DESCRIPTION
**Pull request by JasnaMRB**
See also https://github.com/typelevel/typelevel.github.com/pull/387 as a follow-up

My addition was simply to replace the placeholder image with something else.

### CODE REVIEW

**Review by rossabaker — APPROVED** [review]
LGTM.  In case anyone can't build it, I pushed this commit to https://rossabaker.github.io/typelevel.github.com/.

**Comment by rossabaker** [comment]
Let's merge #387 into this so the site launches together.  There will be further merge conflicts on the placeholder.  Let's decide:

#387 has:

image

#388 has:

image

I actually like the design (particularly the angles) of #387 and the desaturation of #388. 😬

**Comment by rossabaker** [comment]
Option 3:

image

**Comment by jducoeur** [comment]
No passionate opinion, but I like Option 3 slightly more.

**Comment by rossabaker** [comment]
9912648, with the desaturated Typelevel logo ("Option 3") is on the [preview site](https://rossabaker.github.io/typelevel.github.com/blog/).  It includes a merge of @israelperezglez's fixes on #387.  If everyone's happy with that preview, we can launch.

**Comment by JasnaMRB** [comment]
@rossabaker thanks a bunch for the merge conflict help and combining the placeholder image ideas. I did a spot check of the deployed test site and things look good on my android chrome browser, as well as desktop view.

@israelperezglez incredible work on the layout and fixes! We should be planning a blog announcement for it, and we'll be sure to credit you and 47D for your efforts.

**Review by rossabaker — APPROVED** [review]
I'm happy with this as is.

**Pull request merged**
